name: CI

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: kvrhdn/gha-buildevents@v1
        with:
          apikey: ${{ secrets.HONEYCOMB_APIKEY }}
          dataset: go-tfe-run
          job-status: ${{ job.status }}

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v3

      - run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

      - uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.txt

      - run: go vet ./...

  fmt:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: kvrhdn/gha-buildevents@v1
        with:
          apikey: ${{ secrets.HONEYCOMB_APIKEY }}
          dataset: go-tfe-run
          job-status: ${{ job.status }}

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v3

      - name: Formatting
        run: |
          go get golang.org/x/tools/cmd/goimports

          goimports -l -w .
          go mod tidy

          if ! git diff --quiet; then
            echo "Formatting is not okay"
            exit 1
          fi
