name: Integration

on:
  schedule:
    - cron: "0/15 * * * *"

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - uses: kvrhdn/gha-buildevents@v1
        with:
          apikey: ${{ secrets.HONEYCOMB_APIKEY }}
          dataset: go-tfe-run
          job-status: ${{ job.status }}

      - uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - uses: actions/checkout@v2

      - run: go test -v --run Integration
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
